// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package testutil

import (
	"context"
	"tericcabrel/instech/internal/domain"
	"tericcabrel/instech/internal/repository"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRelationshipRepositoryInterface creates a new instance of MockRelationshipRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRelationshipRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRelationshipRepositoryInterface {
	mock := &MockRelationshipRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRelationshipRepositoryInterface is an autogenerated mock type for the RelationshipRepositoryInterface type
type MockRelationshipRepositoryInterface struct {
	mock.Mock
}

type MockRelationshipRepositoryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRelationshipRepositoryInterface) EXPECT() *MockRelationshipRepositoryInterface_Expecter {
	return &MockRelationshipRepositoryInterface_Expecter{mock: &_m.Mock}
}

// CreateRelationship provides a mock function for the type MockRelationshipRepositoryInterface
func (_mock *MockRelationshipRepositoryInterface) CreateRelationship(ctx context.Context, relationship domain.Relationship) (domain.Relationship, error) {
	ret := _mock.Called(ctx, relationship)

	if len(ret) == 0 {
		panic("no return value specified for CreateRelationship")
	}

	var r0 domain.Relationship
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Relationship) (domain.Relationship, error)); ok {
		return returnFunc(ctx, relationship)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Relationship) domain.Relationship); ok {
		r0 = returnFunc(ctx, relationship)
	} else {
		r0 = ret.Get(0).(domain.Relationship)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Relationship) error); ok {
		r1 = returnFunc(ctx, relationship)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRelationshipRepositoryInterface_CreateRelationship_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRelationship'
type MockRelationshipRepositoryInterface_CreateRelationship_Call struct {
	*mock.Call
}

// CreateRelationship is a helper method to define mock.On call
//   - ctx context.Context
//   - relationship domain.Relationship
func (_e *MockRelationshipRepositoryInterface_Expecter) CreateRelationship(ctx interface{}, relationship interface{}) *MockRelationshipRepositoryInterface_CreateRelationship_Call {
	return &MockRelationshipRepositoryInterface_CreateRelationship_Call{Call: _e.mock.On("CreateRelationship", ctx, relationship)}
}

func (_c *MockRelationshipRepositoryInterface_CreateRelationship_Call) Run(run func(ctx context.Context, relationship domain.Relationship)) *MockRelationshipRepositoryInterface_CreateRelationship_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Relationship
		if args[1] != nil {
			arg1 = args[1].(domain.Relationship)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRelationshipRepositoryInterface_CreateRelationship_Call) Return(relationship1 domain.Relationship, err error) *MockRelationshipRepositoryInterface_CreateRelationship_Call {
	_c.Call.Return(relationship1, err)
	return _c
}

func (_c *MockRelationshipRepositoryInterface_CreateRelationship_Call) RunAndReturn(run func(ctx context.Context, relationship domain.Relationship) (domain.Relationship, error)) *MockRelationshipRepositoryInterface_CreateRelationship_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRelationship provides a mock function for the type MockRelationshipRepositoryInterface
func (_mock *MockRelationshipRepositoryInterface) DeleteRelationship(ctx context.Context, id int) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRelationship")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRelationshipRepositoryInterface_DeleteRelationship_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRelationship'
type MockRelationshipRepositoryInterface_DeleteRelationship_Call struct {
	*mock.Call
}

// DeleteRelationship is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockRelationshipRepositoryInterface_Expecter) DeleteRelationship(ctx interface{}, id interface{}) *MockRelationshipRepositoryInterface_DeleteRelationship_Call {
	return &MockRelationshipRepositoryInterface_DeleteRelationship_Call{Call: _e.mock.On("DeleteRelationship", ctx, id)}
}

func (_c *MockRelationshipRepositoryInterface_DeleteRelationship_Call) Run(run func(ctx context.Context, id int)) *MockRelationshipRepositoryInterface_DeleteRelationship_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRelationshipRepositoryInterface_DeleteRelationship_Call) Return(err error) *MockRelationshipRepositoryInterface_DeleteRelationship_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRelationshipRepositoryInterface_DeleteRelationship_Call) RunAndReturn(run func(ctx context.Context, id int) error) *MockRelationshipRepositoryInterface_DeleteRelationship_Call {
	_c.Call.Return(run)
	return _c
}

// GetRelationshipById provides a mock function for the type MockRelationshipRepositoryInterface
func (_mock *MockRelationshipRepositoryInterface) GetRelationshipById(ctx context.Context, id int) (domain.Relationship, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetRelationshipById")
	}

	var r0 domain.Relationship
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (domain.Relationship, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) domain.Relationship); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Relationship)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRelationshipRepositoryInterface_GetRelationshipById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRelationshipById'
type MockRelationshipRepositoryInterface_GetRelationshipById_Call struct {
	*mock.Call
}

// GetRelationshipById is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockRelationshipRepositoryInterface_Expecter) GetRelationshipById(ctx interface{}, id interface{}) *MockRelationshipRepositoryInterface_GetRelationshipById_Call {
	return &MockRelationshipRepositoryInterface_GetRelationshipById_Call{Call: _e.mock.On("GetRelationshipById", ctx, id)}
}

func (_c *MockRelationshipRepositoryInterface_GetRelationshipById_Call) Run(run func(ctx context.Context, id int)) *MockRelationshipRepositoryInterface_GetRelationshipById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRelationshipRepositoryInterface_GetRelationshipById_Call) Return(relationship domain.Relationship, err error) *MockRelationshipRepositoryInterface_GetRelationshipById_Call {
	_c.Call.Return(relationship, err)
	return _c
}

func (_c *MockRelationshipRepositoryInterface_GetRelationshipById_Call) RunAndReturn(run func(ctx context.Context, id int) (domain.Relationship, error)) *MockRelationshipRepositoryInterface_GetRelationshipById_Call {
	_c.Call.Return(run)
	return _c
}

// GetRelationshipsAll provides a mock function for the type MockRelationshipRepositoryInterface
func (_mock *MockRelationshipRepositoryInterface) GetRelationshipsAll(ctx context.Context, params repository.GetRelationshipsAllParams) (repository.PaginatedRelationshipsResult, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for GetRelationshipsAll")
	}

	var r0 repository.PaginatedRelationshipsResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.GetRelationshipsAllParams) (repository.PaginatedRelationshipsResult, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.GetRelationshipsAllParams) repository.PaginatedRelationshipsResult); ok {
		r0 = returnFunc(ctx, params)
	} else {
		r0 = ret.Get(0).(repository.PaginatedRelationshipsResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, repository.GetRelationshipsAllParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRelationshipRepositoryInterface_GetRelationshipsAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRelationshipsAll'
type MockRelationshipRepositoryInterface_GetRelationshipsAll_Call struct {
	*mock.Call
}

// GetRelationshipsAll is a helper method to define mock.On call
//   - ctx context.Context
//   - params repository.GetRelationshipsAllParams
func (_e *MockRelationshipRepositoryInterface_Expecter) GetRelationshipsAll(ctx interface{}, params interface{}) *MockRelationshipRepositoryInterface_GetRelationshipsAll_Call {
	return &MockRelationshipRepositoryInterface_GetRelationshipsAll_Call{Call: _e.mock.On("GetRelationshipsAll", ctx, params)}
}

func (_c *MockRelationshipRepositoryInterface_GetRelationshipsAll_Call) Run(run func(ctx context.Context, params repository.GetRelationshipsAllParams)) *MockRelationshipRepositoryInterface_GetRelationshipsAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repository.GetRelationshipsAllParams
		if args[1] != nil {
			arg1 = args[1].(repository.GetRelationshipsAllParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRelationshipRepositoryInterface_GetRelationshipsAll_Call) Return(paginatedRelationshipsResult repository.PaginatedRelationshipsResult, err error) *MockRelationshipRepositoryInterface_GetRelationshipsAll_Call {
	_c.Call.Return(paginatedRelationshipsResult, err)
	return _c
}

func (_c *MockRelationshipRepositoryInterface_GetRelationshipsAll_Call) RunAndReturn(run func(ctx context.Context, params repository.GetRelationshipsAllParams) (repository.PaginatedRelationshipsResult, error)) *MockRelationshipRepositoryInterface_GetRelationshipsAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetRelationshipsByToolID provides a mock function for the type MockRelationshipRepositoryInterface
func (_mock *MockRelationshipRepositoryInterface) GetRelationshipsByToolID(ctx context.Context, toolID int) ([]domain.Relationship, error) {
	ret := _mock.Called(ctx, toolID)

	if len(ret) == 0 {
		panic("no return value specified for GetRelationshipsByToolID")
	}

	var r0 []domain.Relationship
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]domain.Relationship, error)); ok {
		return returnFunc(ctx, toolID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []domain.Relationship); ok {
		r0 = returnFunc(ctx, toolID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Relationship)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, toolID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRelationshipRepositoryInterface_GetRelationshipsByToolID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRelationshipsByToolID'
type MockRelationshipRepositoryInterface_GetRelationshipsByToolID_Call struct {
	*mock.Call
}

// GetRelationshipsByToolID is a helper method to define mock.On call
//   - ctx context.Context
//   - toolID int
func (_e *MockRelationshipRepositoryInterface_Expecter) GetRelationshipsByToolID(ctx interface{}, toolID interface{}) *MockRelationshipRepositoryInterface_GetRelationshipsByToolID_Call {
	return &MockRelationshipRepositoryInterface_GetRelationshipsByToolID_Call{Call: _e.mock.On("GetRelationshipsByToolID", ctx, toolID)}
}

func (_c *MockRelationshipRepositoryInterface_GetRelationshipsByToolID_Call) Run(run func(ctx context.Context, toolID int)) *MockRelationshipRepositoryInterface_GetRelationshipsByToolID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRelationshipRepositoryInterface_GetRelationshipsByToolID_Call) Return(relationships []domain.Relationship, err error) *MockRelationshipRepositoryInterface_GetRelationshipsByToolID_Call {
	_c.Call.Return(relationships, err)
	return _c
}

func (_c *MockRelationshipRepositoryInterface_GetRelationshipsByToolID_Call) RunAndReturn(run func(ctx context.Context, toolID int) ([]domain.Relationship, error)) *MockRelationshipRepositoryInterface_GetRelationshipsByToolID_Call {
	_c.Call.Return(run)
	return _c
}

// GetToolAlternatives provides a mock function for the type MockRelationshipRepositoryInterface
func (_mock *MockRelationshipRepositoryInterface) GetToolAlternatives(ctx context.Context, toolID int) ([]domain.Relationship, error) {
	ret := _mock.Called(ctx, toolID)

	if len(ret) == 0 {
		panic("no return value specified for GetToolAlternatives")
	}

	var r0 []domain.Relationship
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]domain.Relationship, error)); ok {
		return returnFunc(ctx, toolID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []domain.Relationship); ok {
		r0 = returnFunc(ctx, toolID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Relationship)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, toolID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRelationshipRepositoryInterface_GetToolAlternatives_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetToolAlternatives'
type MockRelationshipRepositoryInterface_GetToolAlternatives_Call struct {
	*mock.Call
}

// GetToolAlternatives is a helper method to define mock.On call
//   - ctx context.Context
//   - toolID int
func (_e *MockRelationshipRepositoryInterface_Expecter) GetToolAlternatives(ctx interface{}, toolID interface{}) *MockRelationshipRepositoryInterface_GetToolAlternatives_Call {
	return &MockRelationshipRepositoryInterface_GetToolAlternatives_Call{Call: _e.mock.On("GetToolAlternatives", ctx, toolID)}
}

func (_c *MockRelationshipRepositoryInterface_GetToolAlternatives_Call) Run(run func(ctx context.Context, toolID int)) *MockRelationshipRepositoryInterface_GetToolAlternatives_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRelationshipRepositoryInterface_GetToolAlternatives_Call) Return(relationships []domain.Relationship, err error) *MockRelationshipRepositoryInterface_GetToolAlternatives_Call {
	_c.Call.Return(relationships, err)
	return _c
}

func (_c *MockRelationshipRepositoryInterface_GetToolAlternatives_Call) RunAndReturn(run func(ctx context.Context, toolID int) ([]domain.Relationship, error)) *MockRelationshipRepositoryInterface_GetToolAlternatives_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRelationship provides a mock function for the type MockRelationshipRepositoryInterface
func (_mock *MockRelationshipRepositoryInterface) UpdateRelationship(ctx context.Context, relationship domain.Relationship) (domain.Relationship, error) {
	ret := _mock.Called(ctx, relationship)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRelationship")
	}

	var r0 domain.Relationship
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Relationship) (domain.Relationship, error)); ok {
		return returnFunc(ctx, relationship)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Relationship) domain.Relationship); ok {
		r0 = returnFunc(ctx, relationship)
	} else {
		r0 = ret.Get(0).(domain.Relationship)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Relationship) error); ok {
		r1 = returnFunc(ctx, relationship)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRelationshipRepositoryInterface_UpdateRelationship_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRelationship'
type MockRelationshipRepositoryInterface_UpdateRelationship_Call struct {
	*mock.Call
}

// UpdateRelationship is a helper method to define mock.On call
//   - ctx context.Context
//   - relationship domain.Relationship
func (_e *MockRelationshipRepositoryInterface_Expecter) UpdateRelationship(ctx interface{}, relationship interface{}) *MockRelationshipRepositoryInterface_UpdateRelationship_Call {
	return &MockRelationshipRepositoryInterface_UpdateRelationship_Call{Call: _e.mock.On("UpdateRelationship", ctx, relationship)}
}

func (_c *MockRelationshipRepositoryInterface_UpdateRelationship_Call) Run(run func(ctx context.Context, relationship domain.Relationship)) *MockRelationshipRepositoryInterface_UpdateRelationship_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Relationship
		if args[1] != nil {
			arg1 = args[1].(domain.Relationship)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRelationshipRepositoryInterface_UpdateRelationship_Call) Return(relationship1 domain.Relationship, err error) *MockRelationshipRepositoryInterface_UpdateRelationship_Call {
	_c.Call.Return(relationship1, err)
	return _c
}

func (_c *MockRelationshipRepositoryInterface_UpdateRelationship_Call) RunAndReturn(run func(ctx context.Context, relationship domain.Relationship) (domain.Relationship, error)) *MockRelationshipRepositoryInterface_UpdateRelationship_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockToolRepositoryInterface creates a new instance of MockToolRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockToolRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockToolRepositoryInterface {
	mock := &MockToolRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockToolRepositoryInterface is an autogenerated mock type for the ToolRepositoryInterface type
type MockToolRepositoryInterface struct {
	mock.Mock
}

type MockToolRepositoryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockToolRepositoryInterface) EXPECT() *MockToolRepositoryInterface_Expecter {
	return &MockToolRepositoryInterface_Expecter{mock: &_m.Mock}
}

// CreateTool provides a mock function for the type MockToolRepositoryInterface
func (_mock *MockToolRepositoryInterface) CreateTool(ctx context.Context, tool domain.Tool) (domain.Tool, error) {
	ret := _mock.Called(ctx, tool)

	if len(ret) == 0 {
		panic("no return value specified for CreateTool")
	}

	var r0 domain.Tool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Tool) (domain.Tool, error)); ok {
		return returnFunc(ctx, tool)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Tool) domain.Tool); ok {
		r0 = returnFunc(ctx, tool)
	} else {
		r0 = ret.Get(0).(domain.Tool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Tool) error); ok {
		r1 = returnFunc(ctx, tool)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockToolRepositoryInterface_CreateTool_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTool'
type MockToolRepositoryInterface_CreateTool_Call struct {
	*mock.Call
}

// CreateTool is a helper method to define mock.On call
//   - ctx context.Context
//   - tool domain.Tool
func (_e *MockToolRepositoryInterface_Expecter) CreateTool(ctx interface{}, tool interface{}) *MockToolRepositoryInterface_CreateTool_Call {
	return &MockToolRepositoryInterface_CreateTool_Call{Call: _e.mock.On("CreateTool", ctx, tool)}
}

func (_c *MockToolRepositoryInterface_CreateTool_Call) Run(run func(ctx context.Context, tool domain.Tool)) *MockToolRepositoryInterface_CreateTool_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Tool
		if args[1] != nil {
			arg1 = args[1].(domain.Tool)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockToolRepositoryInterface_CreateTool_Call) Return(tool1 domain.Tool, err error) *MockToolRepositoryInterface_CreateTool_Call {
	_c.Call.Return(tool1, err)
	return _c
}

func (_c *MockToolRepositoryInterface_CreateTool_Call) RunAndReturn(run func(ctx context.Context, tool domain.Tool) (domain.Tool, error)) *MockToolRepositoryInterface_CreateTool_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTool provides a mock function for the type MockToolRepositoryInterface
func (_mock *MockToolRepositoryInterface) DeleteTool(ctx context.Context, slug string) error {
	ret := _mock.Called(ctx, slug)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTool")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, slug)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockToolRepositoryInterface_DeleteTool_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTool'
type MockToolRepositoryInterface_DeleteTool_Call struct {
	*mock.Call
}

// DeleteTool is a helper method to define mock.On call
//   - ctx context.Context
//   - slug string
func (_e *MockToolRepositoryInterface_Expecter) DeleteTool(ctx interface{}, slug interface{}) *MockToolRepositoryInterface_DeleteTool_Call {
	return &MockToolRepositoryInterface_DeleteTool_Call{Call: _e.mock.On("DeleteTool", ctx, slug)}
}

func (_c *MockToolRepositoryInterface_DeleteTool_Call) Run(run func(ctx context.Context, slug string)) *MockToolRepositoryInterface_DeleteTool_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockToolRepositoryInterface_DeleteTool_Call) Return(err error) *MockToolRepositoryInterface_DeleteTool_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockToolRepositoryInterface_DeleteTool_Call) RunAndReturn(run func(ctx context.Context, slug string) error) *MockToolRepositoryInterface_DeleteTool_Call {
	_c.Call.Return(run)
	return _c
}

// GetToolById provides a mock function for the type MockToolRepositoryInterface
func (_mock *MockToolRepositoryInterface) GetToolById(ctx context.Context, id int) (domain.Tool, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetToolById")
	}

	var r0 domain.Tool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (domain.Tool, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) domain.Tool); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Tool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockToolRepositoryInterface_GetToolById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetToolById'
type MockToolRepositoryInterface_GetToolById_Call struct {
	*mock.Call
}

// GetToolById is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockToolRepositoryInterface_Expecter) GetToolById(ctx interface{}, id interface{}) *MockToolRepositoryInterface_GetToolById_Call {
	return &MockToolRepositoryInterface_GetToolById_Call{Call: _e.mock.On("GetToolById", ctx, id)}
}

func (_c *MockToolRepositoryInterface_GetToolById_Call) Run(run func(ctx context.Context, id int)) *MockToolRepositoryInterface_GetToolById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockToolRepositoryInterface_GetToolById_Call) Return(tool domain.Tool, err error) *MockToolRepositoryInterface_GetToolById_Call {
	_c.Call.Return(tool, err)
	return _c
}

func (_c *MockToolRepositoryInterface_GetToolById_Call) RunAndReturn(run func(ctx context.Context, id int) (domain.Tool, error)) *MockToolRepositoryInterface_GetToolById_Call {
	_c.Call.Return(run)
	return _c
}

// GetToolByIds provides a mock function for the type MockToolRepositoryInterface
func (_mock *MockToolRepositoryInterface) GetToolByIds(ctx context.Context, ids []int) ([]domain.Tool, error) {
	ret := _mock.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for GetToolByIds")
	}

	var r0 []domain.Tool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []int) ([]domain.Tool, error)); ok {
		return returnFunc(ctx, ids)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []int) []domain.Tool); ok {
		r0 = returnFunc(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Tool)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []int) error); ok {
		r1 = returnFunc(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockToolRepositoryInterface_GetToolByIds_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetToolByIds'
type MockToolRepositoryInterface_GetToolByIds_Call struct {
	*mock.Call
}

// GetToolByIds is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []int
func (_e *MockToolRepositoryInterface_Expecter) GetToolByIds(ctx interface{}, ids interface{}) *MockToolRepositoryInterface_GetToolByIds_Call {
	return &MockToolRepositoryInterface_GetToolByIds_Call{Call: _e.mock.On("GetToolByIds", ctx, ids)}
}

func (_c *MockToolRepositoryInterface_GetToolByIds_Call) Run(run func(ctx context.Context, ids []int)) *MockToolRepositoryInterface_GetToolByIds_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []int
		if args[1] != nil {
			arg1 = args[1].([]int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockToolRepositoryInterface_GetToolByIds_Call) Return(tools []domain.Tool, err error) *MockToolRepositoryInterface_GetToolByIds_Call {
	_c.Call.Return(tools, err)
	return _c
}

func (_c *MockToolRepositoryInterface_GetToolByIds_Call) RunAndReturn(run func(ctx context.Context, ids []int) ([]domain.Tool, error)) *MockToolRepositoryInterface_GetToolByIds_Call {
	_c.Call.Return(run)
	return _c
}

// GetToolBySlug provides a mock function for the type MockToolRepositoryInterface
func (_mock *MockToolRepositoryInterface) GetToolBySlug(ctx context.Context, slug string) (domain.Tool, error) {
	ret := _mock.Called(ctx, slug)

	if len(ret) == 0 {
		panic("no return value specified for GetToolBySlug")
	}

	var r0 domain.Tool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (domain.Tool, error)); ok {
		return returnFunc(ctx, slug)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) domain.Tool); ok {
		r0 = returnFunc(ctx, slug)
	} else {
		r0 = ret.Get(0).(domain.Tool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, slug)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockToolRepositoryInterface_GetToolBySlug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetToolBySlug'
type MockToolRepositoryInterface_GetToolBySlug_Call struct {
	*mock.Call
}

// GetToolBySlug is a helper method to define mock.On call
//   - ctx context.Context
//   - slug string
func (_e *MockToolRepositoryInterface_Expecter) GetToolBySlug(ctx interface{}, slug interface{}) *MockToolRepositoryInterface_GetToolBySlug_Call {
	return &MockToolRepositoryInterface_GetToolBySlug_Call{Call: _e.mock.On("GetToolBySlug", ctx, slug)}
}

func (_c *MockToolRepositoryInterface_GetToolBySlug_Call) Run(run func(ctx context.Context, slug string)) *MockToolRepositoryInterface_GetToolBySlug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockToolRepositoryInterface_GetToolBySlug_Call) Return(tool domain.Tool, err error) *MockToolRepositoryInterface_GetToolBySlug_Call {
	_c.Call.Return(tool, err)
	return _c
}

func (_c *MockToolRepositoryInterface_GetToolBySlug_Call) RunAndReturn(run func(ctx context.Context, slug string) (domain.Tool, error)) *MockToolRepositoryInterface_GetToolBySlug_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTool provides a mock function for the type MockToolRepositoryInterface
func (_mock *MockToolRepositoryInterface) UpdateTool(ctx context.Context, tool domain.Tool) (domain.Tool, error) {
	ret := _mock.Called(ctx, tool)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTool")
	}

	var r0 domain.Tool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Tool) (domain.Tool, error)); ok {
		return returnFunc(ctx, tool)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Tool) domain.Tool); ok {
		r0 = returnFunc(ctx, tool)
	} else {
		r0 = ret.Get(0).(domain.Tool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Tool) error); ok {
		r1 = returnFunc(ctx, tool)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockToolRepositoryInterface_UpdateTool_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTool'
type MockToolRepositoryInterface_UpdateTool_Call struct {
	*mock.Call
}

// UpdateTool is a helper method to define mock.On call
//   - ctx context.Context
//   - tool domain.Tool
func (_e *MockToolRepositoryInterface_Expecter) UpdateTool(ctx interface{}, tool interface{}) *MockToolRepositoryInterface_UpdateTool_Call {
	return &MockToolRepositoryInterface_UpdateTool_Call{Call: _e.mock.On("UpdateTool", ctx, tool)}
}

func (_c *MockToolRepositoryInterface_UpdateTool_Call) Run(run func(ctx context.Context, tool domain.Tool)) *MockToolRepositoryInterface_UpdateTool_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Tool
		if args[1] != nil {
			arg1 = args[1].(domain.Tool)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockToolRepositoryInterface_UpdateTool_Call) Return(tool1 domain.Tool, err error) *MockToolRepositoryInterface_UpdateTool_Call {
	_c.Call.Return(tool1, err)
	return _c
}

func (_c *MockToolRepositoryInterface_UpdateTool_Call) RunAndReturn(run func(ctx context.Context, tool domain.Tool) (domain.Tool, error)) *MockToolRepositoryInterface_UpdateTool_Call {
	_c.Call.Return(run)
	return _c
}
