compressionLevel: mixed
defaultSemverRangePrefix: ""

enableHardenedMode: true
enableScripts: false
npmMinimalAgeGate: 4320

httpRetry: 30
nodeLinker: node-modules
npmRegistryServer: "https://registry.npmjs.org"
npmPreapprovedPackages:
  - "@types/*"

checksumBehavior: throw
yarnPath: .yarn/releases/yarn-4.17.0.cjs
