// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"database/sql"
)

type RelationshipRecord struct {
	Id         int
	FromToolId int
	ToToolId   int
	Kind       string
	Metadata   string
	CreatedAt  string
	UpdatedAt  string
}

type ToolRecord struct {
	Id          int
	Name        string
	Slug        string
	Category    string
	SubType     sql.NullString
	Prolang     sql.NullString
	ReleaseYear int
	Devstatus   sql.NullString
	Details     sql.NullString
	UseCases    string
	Tags        string
	Website     sql.NullString
	Github      sql.NullString
	CreatedAt   string
	UpdatedAt   string
}
