// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: relationships.sql

package queries

import (
	"context"
)

const createRelationship = `-- name: CreateRelationship :one
INSERT INTO relationships (from_tool_id, to_tool_id, kind, metadata) VALUES (?, ?, ?, ?) RETURNING id, from_tool_id, to_tool_id, kind, metadata, created_at, updated_at
`

type CreateRelationshipParams struct {
	FromToolId int
	ToToolId   int
	Kind       string
	Metadata   string
}

func (q *Queries) CreateRelationship(ctx context.Context, arg CreateRelationshipParams) (RelationshipRecord, error) {
	row := q.db.QueryRowContext(ctx, createRelationship,
		arg.FromToolId,
		arg.ToToolId,
		arg.Kind,
		arg.Metadata,
	)
	var i RelationshipRecord
	err := row.Scan(
		&i.Id,
		&i.FromToolId,
		&i.ToToolId,
		&i.Kind,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRelationship = `-- name: DeleteRelationship :exec
DELETE FROM relationships WHERE id = ?
`

func (q *Queries) DeleteRelationship(ctx context.Context, id int) error {
	_, err := q.db.ExecContext(ctx, deleteRelationship, id)
	return err
}

const getRelationshipByID = `-- name: GetRelationshipByID :one
SELECT id, from_tool_id, to_tool_id, kind, metadata, created_at, updated_at FROM relationships WHERE id = ? LIMIT 1
`

func (q *Queries) GetRelationshipByID(ctx context.Context, id int) (RelationshipRecord, error) {
	row := q.db.QueryRowContext(ctx, getRelationshipByID, id)
	var i RelationshipRecord
	err := row.Scan(
		&i.Id,
		&i.FromToolId,
		&i.ToToolId,
		&i.Kind,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRelationshipsByToolID = `-- name: GetRelationshipsByToolID :many
SELECT id, from_tool_id, to_tool_id, kind, metadata, created_at, updated_at FROM relationships WHERE from_tool_id = ? OR to_tool_id = ?
`

type GetRelationshipsByToolIDParams struct {
	FromToolId int
	ToToolId   int
}

func (q *Queries) GetRelationshipsByToolID(ctx context.Context, arg GetRelationshipsByToolIDParams) ([]RelationshipRecord, error) {
	rows, err := q.db.QueryContext(ctx, getRelationshipsByToolID, arg.FromToolId, arg.ToToolId)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RelationshipRecord{}
	for rows.Next() {
		var i RelationshipRecord
		if err := rows.Scan(
			&i.Id,
			&i.FromToolId,
			&i.ToToolId,
			&i.Kind,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getToolAlternatives = `-- name: GetToolAlternatives :many
SELECT id, from_tool_id, to_tool_id, kind, metadata, created_at, updated_at FROM relationships WHERE (from_tool_id = ? OR to_tool_id = ?) AND kind = 'alternative_to'
`

type GetToolAlternativesParams struct {
	FromToolId int
	ToToolId   int
}

func (q *Queries) GetToolAlternatives(ctx context.Context, arg GetToolAlternativesParams) ([]RelationshipRecord, error) {
	rows, err := q.db.QueryContext(ctx, getToolAlternatives, arg.FromToolId, arg.ToToolId)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RelationshipRecord{}
	for rows.Next() {
		var i RelationshipRecord
		if err := rows.Scan(
			&i.Id,
			&i.FromToolId,
			&i.ToToolId,
			&i.Kind,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRelationship = `-- name: UpdateRelationship :one
UPDATE relationships SET from_tool_id = ?, to_tool_id = ?, kind = ?, metadata = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ? RETURNING id, from_tool_id, to_tool_id, kind, metadata, created_at, updated_at
`

type UpdateRelationshipParams struct {
	FromToolId int
	ToToolId   int
	Kind       string
	Metadata   string
	Id         int
}

func (q *Queries) UpdateRelationship(ctx context.Context, arg UpdateRelationshipParams) (RelationshipRecord, error) {
	row := q.db.QueryRowContext(ctx, updateRelationship,
		arg.FromToolId,
		arg.ToToolId,
		arg.Kind,
		arg.Metadata,
		arg.Id,
	)
	var i RelationshipRecord
	err := row.Scan(
		&i.Id,
		&i.FromToolId,
		&i.ToToolId,
		&i.Kind,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
