// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tools.sql

package queries

import (
	"context"
	"database/sql"
	"strings"
)

const createTool = `-- name: CreateTool :one
INSERT INTO tools (name, slug, category, sub_type, prolang, release_year, dev_status, details, use_cases, tags, website, github) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) RETURNING id, name, slug, category, sub_type, prolang, release_year, dev_status, details, use_cases, tags, website, github, created_at, updated_at
`

type CreateToolParams struct {
	Name        string
	Slug        string
	Category    string
	SubType     sql.NullString
	Prolang     sql.NullString
	ReleaseYear int
	DevStatus   sql.NullString
	Details     sql.NullString
	UseCases    string
	Tags        string
	Website     sql.NullString
	Github      sql.NullString
}

func (q *Queries) CreateTool(ctx context.Context, arg CreateToolParams) (ToolRecord, error) {
	row := q.db.QueryRowContext(ctx, createTool,
		arg.Name,
		arg.Slug,
		arg.Category,
		arg.SubType,
		arg.Prolang,
		arg.ReleaseYear,
		arg.DevStatus,
		arg.Details,
		arg.UseCases,
		arg.Tags,
		arg.Website,
		arg.Github,
	)
	var i ToolRecord
	err := row.Scan(
		&i.Id,
		&i.Name,
		&i.Slug,
		&i.Category,
		&i.SubType,
		&i.Prolang,
		&i.ReleaseYear,
		&i.DevStatus,
		&i.Details,
		&i.UseCases,
		&i.Tags,
		&i.Website,
		&i.Github,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTool = `-- name: DeleteTool :exec
DELETE FROM tools WHERE slug = ?
`

func (q *Queries) DeleteTool(ctx context.Context, slug string) error {
	_, err := q.db.ExecContext(ctx, deleteTool, slug)
	return err
}

const getToolByID = `-- name: GetToolByID :one
SELECT id, name, slug, category, sub_type, prolang, release_year, dev_status, details, use_cases, tags, website, github, created_at, updated_at FROM tools WHERE id = ? LIMIT 1
`

func (q *Queries) GetToolByID(ctx context.Context, id int) (ToolRecord, error) {
	row := q.db.QueryRowContext(ctx, getToolByID, id)
	var i ToolRecord
	err := row.Scan(
		&i.Id,
		&i.Name,
		&i.Slug,
		&i.Category,
		&i.SubType,
		&i.Prolang,
		&i.ReleaseYear,
		&i.DevStatus,
		&i.Details,
		&i.UseCases,
		&i.Tags,
		&i.Website,
		&i.Github,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getToolBySlug = `-- name: GetToolBySlug :one
SELECT id, name, slug, category, sub_type, prolang, release_year, dev_status, details, use_cases, tags, website, github, created_at, updated_at FROM tools WHERE slug = ? LIMIT 1
`

func (q *Queries) GetToolBySlug(ctx context.Context, slug string) (ToolRecord, error) {
	row := q.db.QueryRowContext(ctx, getToolBySlug, slug)
	var i ToolRecord
	err := row.Scan(
		&i.Id,
		&i.Name,
		&i.Slug,
		&i.Category,
		&i.SubType,
		&i.Prolang,
		&i.ReleaseYear,
		&i.DevStatus,
		&i.Details,
		&i.UseCases,
		&i.Tags,
		&i.Website,
		&i.Github,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getToolsByIDs = `-- name: GetToolsByIDs :many
SELECT id, name, slug, category, sub_type, prolang, release_year, dev_status, details, use_cases, tags, website, github, created_at, updated_at FROM tools WHERE id IN (/*SLICE:ids*/?) ORDER BY name ASC
`

func (q *Queries) GetToolsByIDs(ctx context.Context, ids []int) ([]ToolRecord, error) {
	query := getToolsByIDs
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ToolRecord{}
	for rows.Next() {
		var i ToolRecord
		if err := rows.Scan(
			&i.Id,
			&i.Name,
			&i.Slug,
			&i.Category,
			&i.SubType,
			&i.Prolang,
			&i.ReleaseYear,
			&i.DevStatus,
			&i.Details,
			&i.UseCases,
			&i.Tags,
			&i.Website,
			&i.Github,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTool = `-- name: UpdateTool :one
UPDATE tools SET name = ?, slug = ?, category = ?, sub_type = ?, prolang = ?, release_year = ?, dev_status = ?, details = ?, use_cases = ?, tags = ?, website = ?, github = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ? RETURNING id, name, slug, category, sub_type, prolang, release_year, dev_status, details, use_cases, tags, website, github, created_at, updated_at
`

type UpdateToolParams struct {
	Name        string
	Slug        string
	Category    string
	SubType     sql.NullString
	Prolang     sql.NullString
	ReleaseYear int
	DevStatus   sql.NullString
	Details     sql.NullString
	UseCases    string
	Tags        string
	Website     sql.NullString
	Github      sql.NullString
	Id          int
}

func (q *Queries) UpdateTool(ctx context.Context, arg UpdateToolParams) (ToolRecord, error) {
	row := q.db.QueryRowContext(ctx, updateTool,
		arg.Name,
		arg.Slug,
		arg.Category,
		arg.SubType,
		arg.Prolang,
		arg.ReleaseYear,
		arg.DevStatus,
		arg.Details,
		arg.UseCases,
		arg.Tags,
		arg.Website,
		arg.Github,
		arg.Id,
	)
	var i ToolRecord
	err := row.Scan(
		&i.Id,
		&i.Name,
		&i.Slug,
		&i.Category,
		&i.SubType,
		&i.Prolang,
		&i.ReleaseYear,
		&i.DevStatus,
		&i.Details,
		&i.UseCases,
		&i.Tags,
		&i.Website,
		&i.Github,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
