import { Link, createFileRoute } from '@tanstack/react-router'

export const Route = createFileRoute('/')({ component: App })

function App() {
  return (
    <main className="mx-auto w-full max-w-3xl px-6 py-12">
      <h1 className="mb-3 text-3xl font-semibold">TanStack Start Blank App</h1>
      <p className="mb-8 text-sm text-neutral-600 dark:text-neutral-300">
        This project is scaffolded with TanStack CLI and demonstrates Router,
        Query, and Form integrations with minimal extra scaffolding.
      </p>

      <section className="mb-8">
        <h2 className="mb-2 text-xl font-medium">Library Demos</h2>
        <ul className="list-disc space-y-2 pl-6">
          <li>
            <Link to="/demo/tanstack-query" className="underline">
              TanStack Query demo route
            </Link>
          </li>
          <li>
            <Link to="/demo/form/simple" className="underline">
              TanStack Form simple demo route
            </Link>
          </li>
          <li>
            <Link to="/demo/form/address" className="underline">
              TanStack Form nested-fields demo route
            </Link>
          </li>
        </ul>
      </section>

      <section>
        <h2 className="mb-2 text-xl font-medium">Project Notes</h2>
        <ul className="list-disc space-y-2 pl-6">
          <li>
            File-based routes are generated by TanStack Router into{' '}
            <code>src/routeTree.gen.ts</code>.
          </li>
          <li>
            Query integration is initialized in <code>src/router.tsx</code> via{' '}
            <code>@tanstack/react-router-ssr-query</code>.
          </li>
          <li>
            Run <code>yarn intent:list</code> to inspect available TanStack
            Intent skills.
          </li>
        </ul>
      </section>
    </main>
  )
}
